"""Organise raw images (+ optional YOLO labels) into a processed dataset.

Copies images and labels into a standard layout, prints a dataset summary
(counts, sizes, class distribution, label errors), and can optionally build a
YOLO train/val split for training.

Examples
--------
    python scripts/prepare_data.py --images data/raw/images --labels data/raw/labels --out data/processed
    python scripts/prepare_data.py --images data/raw/images --out data/processed --yolo-split --val-frac 0.2
"""
from __future__ import annotations

import argparse
import shutil
from pathlib import Path

import _common  # noqa: F401
from netinspect.data import format_summary, load_dataset, summarize_dataset
from netinspect.utils import ensure_dir, write_json


def _copy(src: Path, dst_dir: Path) -> None:
    ensure_dir(dst_dir)
    shutil.copy2(src, dst_dir / src.name)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--images", required=True, help="Directory of input images")
    ap.add_argument("--labels", default=None, help="Directory of YOLO .txt labels (optional)")
    ap.add_argument("--out", required=True, help="Output dataset root")
    ap.add_argument("--yolo-split", action="store_true",
                    help="Also build a YOLO images/labels train/val split under <out>/yolo")
    ap.add_argument("--val-frac", type=float, default=0.2, help="Validation fraction")
    args = ap.parse_args()

    out = Path(args.out)
    samples = load_dataset(args.images, args.labels)
    if not samples:
        print(f"No images found in {args.images}. Nothing to do.")
        return

    # 1. Copy into processed/images and processed/labels.
    img_out = ensure_dir(out / "images")
    lbl_out = ensure_dir(out / "labels")
    for s in samples:
        _copy(s.image_path, img_out)
        if s.label_path is not None:
            _copy(s.label_path, lbl_out)

    # 2. Summary.
    summary = summarize_dataset(samples)
    print(format_summary(summary))
    write_json(summary, out / "dataset_summary.json")
    print(f"\nWrote summary to {out / 'dataset_summary.json'}")

    # 3. Optional YOLO split (deterministic by sorted filename).
    if args.yolo_split:
        labelled = [s for s in samples if s.label_path is not None]
        if not labelled:
            print("\n[yolo-split] No labels present; skipping split "
                  "(YOLO training needs labels).")
            return
        n_val = max(1, int(round(len(labelled) * args.val_frac)))
        val = set(s.stem for s in labelled[:n_val])
        root = out / "yolo"
        for split in ("train", "val"):
            ensure_dir(root / "images" / split)
            ensure_dir(root / "labels" / split)
        for s in labelled:
            split = "val" if s.stem in val else "train"
            _copy(s.image_path, root / "images" / split)
            _copy(s.label_path, root / "labels" / split)

        # Emit a ready-to-use Ultralytics dataset YAML with an absolute path so
        # `train_yolo.py --data <root>/dataset.yaml` works without further edits.
        from netinspect.data import DEFAULT_CLASSES
        names = "\n".join(f"  {i}: {c}" for i, c in enumerate(DEFAULT_CLASSES))
        (root / "dataset.yaml").write_text(
            f"# Auto-generated by prepare_data.py --yolo-split\n"
            f"path: {root.resolve().as_posix()}\n"
            f"train: images/train\nval: images/val\nnames:\n{names}\n",
            encoding="utf-8",
        )
        print(f"\n[yolo-split] {len(labelled) - n_val} train / {n_val} val "
              f"images written under {root}")
        print(f"Train with: python scripts/train_yolo.py --data {root.as_posix()}/dataset.yaml")


if __name__ == "__main__":
    main()
